# Generated by Django 4.1.2 on 2022-10-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookphoto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookphoto',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
