# Generated by Django 4.1.2 on 2022-10-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bookphoto_description_bookphoto_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphoto',
            name='Signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myphoto',
            name='how_iam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='myphoto',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
